export const SELECTORS = {
  AUTH: {
    CONTAINER: '.auth-container',
    CARD: '.auth-card',
    LOGO: '.logo',
    LOGO_TEXT: '.logo-text',
    SUBTITLE: '.subtitle',
    ERROR: '.error',
    USERNAME_INPUT: '#username',
    PASSWORD_INPUT: '#password',
    CONFIRM_INPUT: '#confirm',
    SUBMIT_BUTTON: 'button[type="submit"]',
    FORM_GROUP: '.form-group',
  },

  HEADER: {
    ROOT: 'header',
    HEADER_LEFT: '.header-left',
    HEADER_RIGHT: '.header-right',
    LOGO: '.logo',
    LOGO_ICON: '.logo-icon',
    CONNECTION_STATUS: '.connection-status',
    STATUS_DOT: '.status-dot',
    STATUS_TEXT: '.status-text',
    USER_MENU: '.user-menu',
    USER_MENU_TRIGGER: '.user-menu-trigger',
    USER_ICON: '.user-icon',
    USER_DROPDOWN: '.user-dropdown',
    DROPDOWN_USER_HEADER: '.dropdown-user-header',
    DROPDOWN_USERNAME: '.dropdown-username',
    DROPDOWN_ITEM: '.dropdown-item',
    DROPDOWN_DIVIDER: '.dropdown-divider',
    LOGOUT_BUTTON: '.dropdown-item:has-text("Logout")',
    USER_SETTINGS_BUTTON: '.dropdown-item:has-text("Settings")',
    THEME_TOGGLE: '.theme-toggle',
  },

  NAV: {
    TABS: '.tabs',
    TAB_BUTTON: '.tab-btn',
    TAB_OVERVIEW: '.tab-btn:has-text("Overview")',
    TAB_ACTIVITY: '.tab-btn:has-text("Activity")',
    TAB_LOGS: '.tab-btn:has-text("Logs")',
    TAB_SANDBOX: '.tab-btn:has-text("Sandbox")',
    TAB_SETTINGS: '.tab-btn:has-text("Settings")',
    TAB_DEBUG: '.tab-btn:has-text("Debug")',
    ACTIVE_TAB: '.tab-btn.active',
  },

  STATS: {
    GRID: '.stats-grid',
    CARD: '.stat-card',
    VALUE: '.stat-value',
    LABEL: '.stat-label',
    ICON: '.stat-icon',
    TREND: '.stat-trend',
  },

  ACCOUNTS: {
    CARD: '.card',
    CARD_HEADER: '.card-header',
    CARD_TITLE: '.card-title',
    TABLE: 'table',
    TABLE_CONTAINER: '.table-container',
    HEADER_ROW: 'thead tr',
    BODY_ROW: 'tbody tr',
    SELECT_ALL_CHECKBOX: 'thead input[type="checkbox"]',
    ROW_CHECKBOX: 'tbody input[type="checkbox"]',
    NAME_CELL: '.name-cell',
    NAME_CELL_CONTENT: '.name-cell-content',
    ACCOUNT_NAME: '.account-name',
    STATUS_DOT: '.status-dot-inline',
    STATUS_TEXT: '.status-text',
    IDLE_BADGE: '.idle-badge',
    ERROR_INDICATOR: '.error-indicator',
    LLM_INFO: '.llm-info',
    RATE_CELL: '.rate-cell',
    RATE_VALUE: '.rate-value',
    RATE_EMPTY: '.rate-empty',
    TIME_CELL: '.time-cell',
    TIME_VALUE: '.time-value',
    ACTIONS_CELL: '.actions-cell',
    ACTION_BUTTON: '.action-btn',
    DROPDOWN_MENU: '.dropdown-menu',
    DROPDOWN_ITEM: '.dropdown-item',
    BULK_ACTIONS_BAR: '.bulk-actions-bar',
    SELECTION_COUNT: '.selection-count',
    BULK_BUTTONS: '.bulk-buttons',
    EMPTY_STATE: '.empty-state',
  },

  ACTIVITY: {
    CARD: '.card:has(.card-title:has-text("Activity"))',
    SEARCH_INPUT: '.card:has(.card-title:has-text("Activity")) .search-input',
    ACCOUNT_SELECT: '.card:has(.card-title:has-text("Activity")) .filter-select',
    FILTER_DROPDOWN: '.card:has(.card-title:has-text("Activity")) .filter-dropdown-menu',
    FILTER_BUTTON: '.card:has(.card-title:has-text("Activity")) .filter-dropdown-btn',
    FILTER_OPTION: '.filter-option',
    FILTER_CHECKBOX: '.filter-option input[type="checkbox"]',
    EXPORT_BUTTON: '.card:has(.card-title:has-text("Activity")) .export-btn',
    ENTRY_COUNT: '.card:has(.card-title:has-text("Activity")) .entry-count',
    STREAM_TOGGLE: '.card:has(.card-title:has-text("Activity")) .stream-toggle',
    DENSITY_TOGGLE: '.card:has(.card-title:has-text("Activity")) .density-toggle',
    TABLE: '.card:has(.card-title:has-text("Activity")) table',
    TABLE_ROW: '.card:has(.card-title:has-text("Activity")) tbody tr',
    ERROR_ROW: '.error-row',
    ACTION_BADGE: '.badge',
    PREVIEW_BUTTON: '.btn-icon',
    SCROLL_SENTINEL: '.card:has(.card-title:has-text("Activity")) .scroll-sentinel',
    LOADING_INDICATOR: '.loading',
    END_OF_LIST: '.end-of-list',
    EMPTY_STATE: '.card:has(.card-title:has-text("Activity")) .empty',
    TIME_CELL: '.time-cell',
    ACCOUNT_CELL: '.account-cell',
    SUBJECT_CELL: '.subject-cell',
    ACTIONS_CELL: '.actions-cell',
    CONFIDENCE_CELL: '.confidence-cell',
    CONFIDENCE_BADGE: '.confidence-badge',
    CONFIDENCE_HIGH: '.confidence-high',
    CONFIDENCE_MEDIUM: '.confidence-medium',
    CONFIDENCE_LOW: '.confidence-low',
    CONFIDENCE_COLUMN_HEADER: 'th.confidence-col',
  },

  LOGS: {
    CARD: '.card:has(.card-title:has-text("Logs"))',
    SEARCH_INPUT: '.card:has(.card-title:has-text("Logs")) .search-input',
    ACCOUNT_SELECT: '.card:has(.card-title:has-text("Logs")) .filter-select',
    LEVEL_FILTER: '.card:has(.card-title:has-text("Logs")) .filter-dropdown-btn',
    STREAM_TOGGLE: '.card:has(.card-title:has-text("Logs")) .stream-toggle',
    ENTRY_COUNT: '.card:has(.card-title:has-text("Logs")) .entry-count',
    LOG_CONTAINER: '.logs-container',
    LOG_ENTRY: '.log-entry',
    LOG_TIME: '.log-time',
    LOG_LEVEL: '.log-level',
    LOG_CONTEXT: '.log-context',
    LOG_MESSAGE: '.log-message',
    LOG_META: '.log-meta',
    LEVEL_DEBUG: '.level-debug',
    LEVEL_INFO: '.level-info',
    LEVEL_WARN: '.level-warn',
    LEVEL_ERROR: '.level-error',
    EMPTY_STATE: '.empty',
  },

  SETTINGS: {
    CONTAINER: '.settings',
    HEADER: '.settings-header',
    LAYOUT: '.settings-layout',
    SECTION_NAV: '.settings-nav',
    SECTION_BUTTON: '.nav-item',
    ACTIVE_SECTION: '.nav-item.active',
    CONTENT: '.settings-content',
    FORM_GROUP: '.form-group',
    INPUT: 'input',
    SELECT: 'select',
    CHECKBOX: 'input[type="checkbox"]',
    TEXTAREA: 'textarea',
    SAVE_BUTTON: '.settings-header .btn-primary',
    YAML_TOGGLE: '.settings-header .btn-icon',
    YAML_EDITOR: '.yaml-editor',
    YAML_EDITOR_CONTAINER: '.yaml-editor-container',
    YAML_WARNING: '.yaml-warning',
    ADD_ACCOUNT_BUTTON: '.settings-content button:has-text("+")',
    ADD_PROVIDER_BUTTON: '.settings-content button:has-text("+")',
    ACCOUNTS_SECTION: '.nav-item:has-text("Email Accounts")',
    PROVIDERS_SECTION: '.nav-item:has-text("LLM Providers")',
    GLOBAL_SECTION: '.nav-item:has-text("Global Settings")',
    API_KEYS_SECTION: '.nav-item:has-text("API Keys")',
    MODULES_SECTION: '.nav-item:has-text("Modules")',
    TEST_BUTTON: 'button:has-text("Test")',
    PROBE_BUTTON: 'button:has-text("Probe")',
    CONFIG_SECTION: '.config-section',
    BTN_SECONDARY: '.btn-secondary',
    BTN_PRIMARY: '.btn-primary',
    BTN_ICON: '.btn-icon',
  },

  SIDEBAR: {
    CONTAINER: '.sidebar',
    PANEL: '.panel',
    PANEL_TITLE: '.panel-title',
    SERVICES_LIST: '.services-list',
    SERVICE_ITEM: '.service-item',
    SERVICE_INDICATOR: '.service-indicator',
    SERVICE_NAME: '.service-name',
    SERVICE_STATUS: '.service-status',
    PROVIDER_LIST: '.provider-list',
    PROVIDER_CARD: '.provider-card',
    PROVIDER_NAME: '.provider-name',
    PROVIDER_HEADER: '.provider-header',
    PROVIDER_MODEL: '.provider-model',
    PROVIDER_METRICS: '.provider-metrics',
    HEALTH_INDICATOR: '.health-indicator',
    METRIC: '.metric',
    METRIC_VALUE: '.metric-value',
    METRIC_LABEL: '.metric-label',
    RATE_LIMIT_WARNING: '.rate-limit-warning',
  },

  DEBUG: {
    CONTAINER: '.debug',
    HEADER: '.debug-header',
    GRID: '.debug-grid',
    SECTION: '.debug-section',
    SECTION_TITLE: '.debug-section h3',
    REFRESH_BUTTON: '.refresh-icon-btn',
    TEST_ALL_BUTTON: '.btn-small',
    DEBUG_ITEMS: '.debug-items',
    DEBUG_ITEM: '.debug-item',
    DEBUG_LABEL: '.debug-label',
    DEBUG_VALUE: '.debug-value',
    DEBUG_META: '.debug-meta',
    STATUS_BADGE: '.status-badge',
    STATUS_DOT: '.status-dot',
    STATUS_HEALTHY: '.status-badge.healthy',
    STATUS_DISABLED: '.status-badge.disabled',
    STATUS_PARTIAL: '.status-badge.partial',
    STATUS_TESTING: '.status-badge.testing',
    PROVIDER_TEST_BUTTON: '.provider-test-btn',
    TESTING_SPINNER: '.testing-spinner',
    SERVER_ITEM: '.server-item',
    SERVER_HEADER: '.server-header',
    SERVER_ACCOUNTS: '.server-accounts',
    ACCOUNT_ROW: '.account-row',
    BADGE_ERRORS: '.badge-errors',
    BADGE_IDLE: '.badge-idle',
    BADGE_PAUSED: '.badge-paused',
  },

  CHARTS: {
    BAR_CHART: '.bar-chart',
    PIE_CHART: '.pie-chart',
    CHART_LEGEND: '.chart-legend',
    CHART_BAR: '.chart-bar',
    CHART_SLICE: '.chart-slice',
  },

  MODAL: {
    CONTAINER: '.modal',
    BACKDROP: '.modal-backdrop',
    CONTENT: '.modal-content',
    HEADER: '.modal-header',
    TITLE: '.modal-title',
    CLOSE_BUTTON: '.modal-close',
    BODY: '.modal-body',
    FOOTER: '.modal-footer',
    CANCEL_BUTTON: '.btn-cancel',
    CONFIRM_BUTTON: '.btn-confirm',
    DANGER_BUTTON: '.btn-danger',
    HEADER_ROW: '.modal-header-row',
    HEADER_ACTIONS: '.modal-header-actions',
    HEADER_ACTION_BTN: '.header-action-btn',
    HEADER_BADGE: '.header-badge',
    HEADER_DROPDOWN_WRAPPER: '.header-dropdown-wrapper',
    HEADER_DROPDOWN_MENU: '.header-dropdown-menu',
    SIDE_MODAL: '.side-modal',
    SIDE_MODAL_HEADER: '.side-modal-header',
    SIDE_MODAL_CONTENT: '.side-modal-content',
  },

  TOAST: {
    CONTAINER: '.toast-container',
    TOAST: '.toast',
    SUCCESS: '.toast-success',
    ERROR: '.toast-error',
    WARNING: '.toast-warning',
    INFO: '.toast-info',
    MESSAGE: '.toast-message',
    CLOSE_BUTTON: '.toast-close',
  },

  BANNER: {
    DRY_RUN: '.dry-run-banner',
    UPDATE: '.update-banner',
    VERSION_MISMATCH: '.version-mismatch-banner',
    REFRESH_BUTTON: 'button:has-text("Refresh")',
    DISMISS_BUTTON: 'button:has-text("Dismiss")',
  },

  FOOTER: {
    ROOT: '.footer',
    VERSION: '.version',
    GITHUB_LINK: 'a[href*="github"]',
    UPDATE_LINK: '.update-link',
  },

  EMAIL_PREVIEW: {
    MODAL: '.email-preview-modal',
    SUBJECT: '.preview-subject',
    FROM: '.preview-from',
    DATE: '.preview-date',
    BODY: '.preview-body',
    ACTIONS: '.preview-actions',
    CLOSE_BUTTON: '.preview-close',
  },

  SANDBOX: {
    CONTAINER: '.sandbox-container',
    LAYOUT: '.sandbox-layout',
    PROMPT_PANEL: '.prompt-panel',
    EMAIL_PANEL: '.email-panel',
    CONFIG_PANEL: '.config-panel',
    PANEL_HEADER: '.panel-header',
    PANEL_CONTENT: '.panel-content',
    HEADER_CONTROLS: '.header-controls',
    UPLOAD_BTN: '.upload-btn',
    UPLOAD_BTN_UNAVAILABLE: '.upload-btn.unavailable',
    TOGGLE_RAW: '.toggle-raw-btn',
    FILE_INPUT: 'input[type="file"]',
    EMAIL_FROM: '#email-from',
    EMAIL_TO: '#email-to',
    EMAIL_SUBJECT: '#email-subject',
    EMAIL_BODY: '#email-body',
    RAW_EMAIL: '#raw-email',
    PROVIDER_SELECT: '#provider',
    MODEL_INPUT: '#model',
    FOLDER_MODE_PREDEFINED: 'input[type="radio"][value="predefined"]',
    FOLDER_MODE_AUTO: 'input[type="radio"][value="auto_create"]',
    ALLOWED_FOLDERS: '#allowed-folders',
    EXISTING_FOLDERS: '#existing-folders',
    ACTION_TOGGLES: '.action-toggles',
    ACTION_TOGGLE: '.action-toggle',
    ACTION_TOGGLE_ACTIVE: '.action-toggle.active',
    RUN_TEST_BTN: '.btn-run',
    RESULTS_SECTION: '.results-section',
    RESULTS_HEADER: '.results-header',
    RESULTS_TABS: '.results-tabs',
    RESULTS_TAB: '.tab',
    RESULTS_TAB_ACTIVE: '.tab.active',
    RESULTS_CONTENT: '.results-content',
    ACTIONS_LIST: '.actions-list',
    ACTION_CARD: '.action-card',
    PROMPT_PREVIEW: '.prompt-preview',
    RAW_RESPONSE: '.raw-response',
    LATENCY: '.latency',
    STATUS_SUCCESS: '.status.success',
    STATUS_ERROR: '.status.error',
    ERROR_MESSAGE: '.error-message',
    CONFIDENCE_SECTION: '.confidence-section',
    CONFIDENCE_SCORE: '.confidence-score',
    CONFIDENCE_VALUE: '.confidence-value',
    REASONING: '.reasoning',
    REASONING_TEXT: '.reasoning-text',
    USAGE_INFO: '.usage-info',
    USAGE_ITEM: '.usage-item',
    USAGE_VALUE: '.usage-value',
    ATTACHMENT_PREVIEW: '.attachment-preview',
    ATTACHMENT_HEADER: '.attachment-header',
    ATTACHMENT_INFO: '.attachment-info',
    ATTACHMENT_NAME: '.attachment-name',
    ATTACHMENT_SIZE: '.attachment-size',
    ATTACHMENT_TRUNCATED: '.attachment-truncated',
    ATTACHMENT_TEXT: '.attachment-text',
    REMOVE_ATTACHMENT: '.remove-attachment',
    UPLOAD_ERROR: '.upload-error',
    LOADING_STATE: '.loading-state',
    ERROR_STATE: '.error-state',
  },

  COMMON: {
    LOADING: '.loading',
    LOADING_SPINNER: '.spinner',
    EMPTY_STATE: '.empty-state',
    ERROR_STATE: '.error-state',
    CARD: '.card',
    CARD_TITLE: '.card-title',
    CARD_CONTENT: '.card-content',
    BUTTON: 'button',
    LINK: 'a',
    TOOLTIP: '.tooltip',
  },
} as const;

export type SelectorKey = keyof typeof SELECTORS;
