import { loader } from 'fumadocs-core/source';
import { createMDXSource } from 'fumadocs-mdx';

// This will be auto-generated by fumadocs-mdx
import { docs, meta } from '@/.source';

export const source = loader({
  baseUrl: '/docs',
  source: createMDXSource(docs, meta),
});

export const { getPage, getPages, pageTree } = source;

export const baseOptions = {
  pageTree,
};
